name: Build notification

on: push

jobs:
  echo-build-started:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Echo Build Started
        run: echo "Build started"
